update: all
branch: master
schedule: "every month"
search: True
close_prs: True
requirements:
  - tests/requirements.txt:
      update: False
  - simple_template_server/requirements.txt:
      update: False
