sudo: required
services:
  - docker
language: python
env:
  global:
    # Docker
    - DOCKER_REPOSITORY=mozorg/snippets
    # Django
    - DEBUG=False
    - SECURE_SSL_REDIRECT=False
    - ALLOWED_HOSTS=*
    - SECRET_KEY=foo
    - DATABASE_URL=mysql://root@db/snippets
    - SITE_URL=http://localhost:8000
    - CACHE_URL=dummy://
    - ENABLE_ADMIN=True
before_install:
  - docker --version
  - echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile
install:
  - docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} --pull=true .
before_script:
  - env > .env
script:
  - docker run -d --name mariadb -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -e MYSQL_DATABASE=snippets mariadb:10.0
  - docker run ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} flake8 snippets
  # Wait mysql to initialize.
  - docker run --link mariadb:db -e CHECK_PORT=3306 -e CHECK_HOST=db giorgos/takis
  - docker run --env-file .env --link mariadb:db ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} ./manage.py test --parallel
