version: '3.4'
services:
  db:
    image: mariadb:10.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=snippets
  web:
    build:
      context: .
      args:
        DEVELOPMENT: "true"
    ports:
      - "8443:8443"
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - DATABASE_URL=mysql://root@db/snippets
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - SECRET_KEY=59114b6a-2858-4caf-8878-482a24ee9542
      - ENABLE_ADMIN=True
      - CSP_REPORT_ONLY=True
      - CSP_REPORT_ENABLE=False
    command:
      ./bin/run-dev.sh
